### ISSUE TITLE
TS import

### ISSUE THREAD

**Issue by joscha** [Olical/EventEmitter#137]
When using:
```ts
import EventEmitter = require("wolfy87-eventemitter");
```
with:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
  }
}
```
I get
```
2 import EventEmitter = require("wolfy87-eventemitter");
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/bla.ts(2,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.


2 import EventEmitter = require("wolfy87-eventemitter");
```

Unfortunately when doing:
```ts
import * as EventEmitter from "wolfy87-eventemitter";
```
I get
```
/Users/joscha/dev/xhr-mocklet/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/MockXMLHttpRequestUpload.ts (1,31): Module '"/Users/joscha/dev/xhr-mocklet/node_modules/wolfy87-eventemitter/EventEmitter"' resolves to a non-module entity and cannot be imported using this construct. (2497)
    at getOutput (/Users/joscha/dev/xhr-mocklet/node_modules/ts-node/src/index.ts:307:15)
    at /Users/joscha/dev/xhr-mocklet/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/joscha/dev/xhr-mocklet/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/Users/joscha/dev/xhr-mocklet/node_modules/ts-node/src/index.ts:392:43)
```

I am not 100% sure, but I think the types might not be defined in a compatible way to be used with the tsconfig options above - any ideas?

**Comment by Olical** [comment]
I'm afraid I've never seen that import / require syntax before and I don't know what the error means. I didn't add the TS definitions to this repository myself since I don't use it or intend to use it. Can you see anything wrong with [the `.ts` file](https://github.com/Olical/EventEmitter/blob/master/EventEmitter.d.ts)?

I won't be of much help here since I know far less about it than you do. Hopefully someone who knows more about TS can help us out if you're not sure.

**Comment by Olical** [comment]
Without further information, I don't think I can help here I'm afraid. Maybe try the version from Definitely Typed? (I think that's what it's called?...)
